; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Ether Music"
#define MyAppVersion "2.1.4"
#define MyAppPublisher "GZXiaoBai"
#define MyAppURL "https://github.com/GZXiaoBai/ether-music"
#define MyAppExeName "ether_music.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8A296560-4966-4190-8884-187515255470}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=..\installer_output
OutputBaseFilename=EtherMusic_Setup_v{#MyAppVersion}
SetupIconFile=..\windows\runner\resources\app_icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "cleaninstall"; Description: "全新安装 (清除所有数据和设置)"; GroupDescription: "安装类型"; Flags: unchecked

[Files]
; IMPORTANT: You must run "flutter build windows --release" before compiling this script.
Source: "..\build\windows\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\build\windows\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
// Helper function to locate the data directory
function GetDataDir(Param: String): String;
begin
  // Based on your Runner.rc: CompanyName="com.ether", ProductName="ether_music"
  // Flutter path_provider usually maps to {userappdata}\CompanyName\ProductName
  // or just {userappdata}\ProductName if CompanyName is empty.
  // Here we target: %APPDATA%\com.ether\ether_music
  Result := ExpandConstant('{userappdata}\com.ether\ether_music');
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  DataDir: String;
begin
  if CurStep = ssInstall then
  begin
    // Check if the user selected "Clean Install"
    if IsTaskSelected('cleaninstall') then
    begin
      DataDir := GetDataDir('');
      if DirExists(DataDir) then
      begin
        Log('Performing Clean Install: Deleting data directory ' + DataDir);
        // Delete the directory and everything inside it
        DelTree(DataDir, True, True, True);
      end;
    end;
  end;
end;
